name: check-version-number
on:
  pull_request:
    branches:
      - main
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check version numbert
        run: |
            VERSION_TAG=v$(cat pubspec.yaml | grep -Po '(?<=version:\s)(.*)')
            TAG_FOUND=$(git tag -l | grep -c $VERSION_TAG)
            if [ "$TAG_FOUND" -eq "0" ]; then
              exit 0
            fi
            echo "Version number already exists"
            exit 1
        