name: check-version-number
on:
  pull_request:
    branches:
      - main
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check version numbert
        run: |
            VERSION_TAG=v$(cat pubspec.yaml | grep -Po '(?<=version:\s)(.*)')
        